"""
Family invitation data access layer

Provides CRUD and query logic for family_invitations table.
Handles queries needed for status transitions (pending → accepted/declined/cancelled/expired)
in service layer.

Main query patterns:
- Single invitation lookup by token (public accept/decline flow)
- Duplicate invitation check with (family_id, email, status=pending)
- List lookup with family_id + pending status (owner dashboard)
- Expiration filtering based on expires_at
"""

from datetime import datetime, timezone
from typing import Optional
from uuid import UUID

from sqlalchemy.orm import Session, joinedload

from backend.models.family_invitation import FamilyInvitation


class FamilyInvitationRepository:
    """
    Family invitation data access class

    Provides CRUD and status management methods for family_invitations table.
    """

    def __init__(self, db: Session):
        """Inject database session"""
        self.db = db

    def find_by_token(self, token: UUID) -> Optional[FamilyInvitation]:
        """
        Find invitation by UUID token (includes family, inviter join)

        Args:
            token: UUID included in invitation link

        Returns:
            FamilyInvitation | None: Matching invitation record or None
        """
        return (
            self.db.query(FamilyInvitation)
            .options(
                joinedload(FamilyInvitation.family),
                joinedload(FamilyInvitation.inviter),
            )
            .filter(FamilyInvitation.token == token)
            .first()
        )

    def find_by_id(self, invitation_id: int) -> Optional[FamilyInvitation]:
        """
        Find by invitation ID (includes family, inviter join)

        Args:
            invitation_id: Invitation unique ID

        Returns:
            FamilyInvitation | None
        """
        return (
            self.db.query(FamilyInvitation)
            .options(
                joinedload(FamilyInvitation.family),
                joinedload(FamilyInvitation.inviter),
            )
            .filter(FamilyInvitation.id == invitation_id)
            .first()
        )

    def find_pending_by_family_and_email(
        self, family_id: int, email: str
    ) -> Optional[FamilyInvitation]:
        """
        Check existence of pending invitation by (family_id, email) combination

        Used to prevent duplicate invitations.

        Args:
            family_id: Family ID
            email: Target invitation email (delivered after lowercase normalization)

        Returns:
            FamilyInvitation | None: Pending status invitation or None
        """
        return (
            self.db.query(FamilyInvitation)
            .filter(
                FamilyInvitation.family_id == family_id,
                FamilyInvitation.email == email,
                FamilyInvitation.status == "pending",
                FamilyInvitation.expires_at > datetime.now(timezone.utc),
            )
            .first()
        )

    def find_pending_by_family_id(self, family_id: int) -> list[FamilyInvitation]:
        """
        Find pending invitation list by family_id (excludes expired)

        Used to show ongoing invitation list on owner dashboard.

        Args:
            family_id: Family ID

        Returns:
            list[FamilyInvitation]: pending + non-expired invitation list (creation date desc)
        """
        return (
            self.db.query(FamilyInvitation)
            .options(joinedload(FamilyInvitation.inviter))
            .filter(
                FamilyInvitation.family_id == family_id,
                FamilyInvitation.status == "pending",
                FamilyInvitation.expires_at > datetime.now(timezone.utc),
            )
            .order_by(FamilyInvitation.created_at.desc())
            .all()
        )

    def create(
        self,
        family_id: int,
        inviter_user_id: int,
        email: str,
        suggested_name: Optional[str],
        suggested_phone: Optional[str],
        suggested_age: Optional[int],
        expires_at: datetime,
    ) -> FamilyInvitation:
        """
        Create new invitation record (token is auto-generated by model default)

        Args:
            family_id: Family ID to invite to
            inviter_user_id: User ID who sends invitation
            email: Target invitation email (delivered after lowercase normalization)
            suggested_name: Name suggested by admin (for reference)
            suggested_phone: Suggested phone number
            suggested_age: Suggested age
            expires_at: Expiration time (UTC)

        Returns:
            FamilyInvitation: Created invitation record (flush completed)
        """
        invitation = FamilyInvitation(
            family_id=family_id,
            inviter_user_id=inviter_user_id,
            email=email,
            suggested_name=suggested_name,
            suggested_phone=suggested_phone,
            suggested_age=suggested_age,
            expires_at=expires_at,
        )
        self.db.add(invitation)
        self.db.flush()
        return invitation

    def update_status(
        self,
        invitation: FamilyInvitation,
        status: str,
        timestamp_field: Optional[str] = None,
        timestamp_value: Optional[datetime] = None,
    ) -> FamilyInvitation:
        """
        Update invitation status

        Args:
            invitation: Invitation entity to update
            status: New status value (accepted / declined / cancelled / expired)
            timestamp_field: Timestamp column name to set (e.g. 'accepted_at')
            timestamp_value: Time value to set

        Returns:
            FamilyInvitation: Updated entity (flush completed)
        """
        invitation.status = status
        if timestamp_field and timestamp_value:
            setattr(invitation, timestamp_field, timestamp_value)
        self.db.flush()
        return invitation
