"""
Scan log management API router

Provides API endpoints for recording and querying RFID scan events.
Each scan event is recorded as FOUND/LOST status and provides basic data for belongings tracking.

Main endpoints:
- POST /: Register new scan log (manual)
- GET /{member_id}: Query specific family member's scan history

Business logic:
- Scan logs are mainly auto-generated by Lambda functions
- Also supports manual registration (for debugging and testing)
- Only family members can query each other's scan history
- Rate limiting applied (prevent API abuse)

Data format:
- Scan time (UTC)
- Tag UID
- Scan status (FOUND/LOST)
- Associated item information

Security: JWT authentication required, family-unit data isolation
"""

from fastapi import APIRouter, Depends, Request
from sqlalchemy.orm import Session

from backend.common.dependencies import get_current_user
from backend.common.db import get_db
from backend.common.exceptions import BadRequestException
from backend.common.response import success_response
from backend.common.route_decorators import handle_service_errors, validate_positive_id
from backend.common.rate_limiter import limiter, api_rate_limit
from backend.schemas.scan_log_schema import ScanLogCreateRequest
from backend.services.scan_log_service import ScanLogService


router = APIRouter(tags=["scan-logs"])


@router.post("", response_model=dict)
@limiter.limit(api_rate_limit)
@handle_service_errors
def create_scan_log(
    request: Request,
    payload: ScanLogCreateRequest,
    current_user=Depends(get_current_user),
    db: Session = Depends(get_db)
):
    validate_positive_id("item_id", payload.item_id or 0)

    scan_log_service = ScanLogService(db)
    result = scan_log_service.create_scan_log(
        user_id=current_user.id,
        item_id=payload.item_id,
        status=payload.status
    )
    return success_response(data=result.model_dump())
